ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_approved" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "approved_by" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "approved_at" TIMESTAMPTZ;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "requested_role" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "requested_agency" TEXT;
